routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use  App\Http\Controllers\ParticipanteController;
use App\Http\Controllers\CiudadController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//Ruta para mostrar la lista de participantes en el index
Route::resource('participantes', ParticipanteController::class);

Route::resource('ciudades', CiudadController::class);

app/Models/Ciudad.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Ciudad extends Model
{
    use HasFactory;
    protected  $table = 'ciudades';
    protected  $fillable=['id','nombre'];
    public $timestamps = false;

  

}

app/Models/Participante.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Participante extends Model
{
    use HasFactory;
    protected $fillable = [
        'carnet_identidad',
        'nombres',
        'apellidos',
        'sexo',
        'direccion',
        'correo_electronico',
        'celular',
        'ciudad_id'
    ];
    public function ciudad(){
        return $this->belongsTo(Ciudad::class,'ciudad_id','id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/CiudadController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ciudad;
use Illuminate\Http\Request;

class CiudadController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
       return view('ciudades.index', [
            'ciudades' => Ciudad::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(Ciudad $ciudad)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Ciudad $ciudad)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Ciudad $ciudad)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Ciudad $ciudad)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/ParticipanteController.php
<?php
namespace App\Http\Controllers;
use App\Models\Participante;
use Illuminate\Http\Request;
use App\Models\Ciudad;
class ParticipanteController extends Controller
{
    public function index()
    {
        $participantes = Participante::all();
        return view('participantes.index', [
            'participantes' => $participantes
        ]);
    }
    public function create()
    {
        $ciudades = Ciudad::all();
        return view('participantes.create', [
            'ciudades' => $ciudades
        ]);
    }
    public function store(Request $request)
    {
        Participante::create($request->all());
        return redirect()->route('participantes.index');
    }
    public function show(Participante $participante)
    {
        //
    }
    public function edit(Participante $participante)
    {
        $ciudades = Ciudad::all();
        return view('participantes.edit', [
            'participante' => $participante,
            'ciudades' => $ciudades
        ]);
    }
    public function update(Request $request, Participante $participante)
    {
        $participante->update($request->all());
        return redirect()->route('participantes.index');
    }
    public function destroy(Participante $participante)
    {
        $participante->delete();
        return redirect()->route('participantes.index');
    }
}

resources/views/ciudades/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <table>
        <tr>
            <th>Nombres</th>
            <th>Operaciones</th>

        </tr>
        
    </table>

    <a href="{{route('ciudades.create')}}">Insertar Ciudad</a>
    
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Laravel App</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">

    <!-- Sidebar -->
    <div class="h-screen w-64 bg-gray-800 text-gray-100 fixed top-0 left-0 overflow-y-auto ">
        <div class="p-4">
            <h class="text-lg font-bold">CCBOL Sucre 2024</h>
            <!-- Add your sidebar menu items here -->
            <ul class="mt-4">
                <li><a href="/" class="block py-2 px-4 text-white hover:bg-gray-700">Cuadro</a></li>
                <li><a href="{{route('participantes.index')}}" class="block py-2 px-4 text-white hover:bg-gray-700">Participantes</a></li>
                <li><a href="{{route('ciudades.index')}}" class="block py-2 px-4 text-white hover:bg-gray-700">Ciudad</a></li>
                <!-- Add more menu items as needed -->
            </ul>
        </div>
    </div>

    <!-- Content Area -->
    <div class="ml-64 p-4 "> <!-- ml-64 to offset the sidebar width -->
        <!-- Header -->
        <header class="bg-white shadow-md p-4 mb-4 hidden">
            <div class="flex justify-between items-center">
                <div>
                    <h2 class="text-lg font-semibold">Welcome, User!</h2>
                </div>
                <div>
                    <!-- Add any header actions or components here -->
                </div>
            </div>
        </header>

        <!-- Main Content Area -->
        <div class="bg-white p-6 shadow-md">
            @yield('content')

        </div>
    </div>

</body>
</html>

resources/views/participantes/create.blade.php
@extends('layouts.app')

@section('content')

    <form action="{{route('participantes.store')}}" method="post">
        @csrf
        <label for="nombres">Carnet Identidad</label>
        <input type="text" name="carnet_identidad">
        <br>
        <label for="nombres">Nombres</label>
        <input type="text" name="nombres">
        <br>
        <label for="apellidos">Apellidos</label>
        <input type="text" name="apellidos">
        <br>
        <label for="sexo">Sexo</label>
        <input type="radio" name="sexo" value="M">M
        <input type="radio" name="sexo" value="F">F
        <br>
        <label for="direccion">Direccion</label>
        <input type="text" name="direccion">
        <br>
        <label for="correo_electronico">Correo Electronico</label>
        <input type="email" name="correo_electronico">
        <br>
        <label for="celular">Celular</label>
        <input type="text" name="celular">
        <br>
        <label for="ciudad">Ciudad</label>
        <select name="ciudad_id">
            @foreach ($ciudades as $ciudad)
            <option value="{{$ciudad->id}}">{{$ciudad->nombre}}</option>
            @endforeach
        </select>
        <br>
        <input type="submit" value="Registrar">






    </form>

    @endsection

resources/views/participantes/edit.blade.php
@extends('layouts.app')

@section('content')

<form class="w-full max-w-lg" action="{{route('participantes.update',$participante->id)}}" method="post">
    @csrf
    @method('PUT')
    <label class="block uppercase tracking-wide text-red-500 text-xs font-bold mb-5"  for="nombres">Carnet Identidad</label>
    <input class="appearance-none block w-full lg:1/2 bg-gray-200 text-gray-700 border  rounded py-2 px-3  leading-tight focus:outline-none focus:bg-white" id="grid-first-name" type="text" name="carnet_identidad" value="{{$participante->carnet_identidad}}">
    <label for="nombres">Nombres</label>
    <input class="appearance-none block w-full lg:1/2 bg-gray-200 text-gray-700 border  rounded py-2 px-3  leading-tight focus:outline-none focus:bg-white" type="text" name="nombres" value="{{$participante->nombres}}">
    <label for="apellidos">Apellidos</label>
    <input class="appearance-none block w-full lg:1/2 bg-gray-200 text-gray-700 border  rounded py-2 px-3  leading-tight focus:outline-none focus:bg-white" type="text" name="apellidos" value="{{$participante->apellidos}}">
    <br>
    <label for="sexo">Sexo</label>

    <input type="radio" name="sexo" value="M" @checked($participante->sexo=='M')>M
    <input type="radio" name="sexo" value="F" @checked($participante->sexo=='F')>F
    <br>
    <label for="direccion">Direccion</label>
    <input class="appearance-none block w-full lg:1/2 bg-gray-200 text-gray-700 border  rounded py-2 px-3 leading-tight focus:outline-none focus:bg-white" type="text" name="direccion" value="{{$participante->direccion}}">
    <br>
    <label for="correo_electronico">Correo Electronico</label>
    <input class="appearance-none block w-full lg:1/2 bg-gray-200 text-gray-700 border  rounded py-2 px-3  leading-tight focus:outline-none focus:bg-white" type="email" name="correo_electronico" value="{{$participante->correo_electronico}}">
    <br>
    <label for="celular">Celular</label>
    <input class="appearance-none block w-full lg:1/2 bg-gray-200 text-gray-700 border  rounded py-2 px-3 leading-tight focus:outline-none focus:bg-white" type="text" name="celular" value="{{$participante->celular}}">
    <br>
    <label for="ciudad">Ciudad</label>
    <select
    class="relative z-20 w-full appearance-none rounded border border-stroke bg-transparent px-5 py-3 outline-none transition " name="ciudad_id">

        @foreach ($ciudades as $ciudad)
        <option value="{{$ciudad->id}}" @selected($ciudad->id==$participante->ciudad_id) >{{$ciudad->nombre}}
        </option>
        @endforeach
    </select>
    <br>
    <input class="py-2 px-2 rounded transition ease-in-out delay-150 bg-blue-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300" type="submit" value="Actualizar">
   






</form>
@endsection

resources/views/participantes/index.blade.php
@extends('layouts.app')

@section('content')

    <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
        <tr>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Sexo</th>
            <th>Direccion</th>
            <th>Correo Electronico</th>
            <th>Celular</th>
            <th>Ciudad</th>
            <th>Operaciones</th>

        </tr>
        @foreach ($participantes as $participante)
        <tr>
            <td>{{$participante->nombres}}</td>
            <td>{{$participante->apellidos}}</td>
            <td>{{$participante->sexo}}</td>
            <td>{{$participante->direccion}}</td>
            <td>{{$participante->correo_electronico}}</td>
            <td>{{$participante->celular}}</td>
            <td>{{$participante->ciudad->nombre}}</td>
            <td>
                <a class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" href="{{route('participantes.edit',$participante->id)}}">Editar</a>
                <form action="{{route('participantes.destroy',$participante->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <input class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" type="submit" value="Eliminar">
                </form>
            </td>
        </tr>
        @endforeach   

    </table>

    <a href="{{route('participantes.create')}}">Insertar Participante</a>
    @endsection